<a href="https://colab.research.google.com/github/yumehara/hackday_2022/blob/main/notebooks/spending.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 2020年度 市町村ごとの歳出データ

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import os
import pandas as pd

In [3]:
DIR_NAME = '/content/drive/MyDrive/hackday/'

In [4]:
df_spending = pd.read_csv(os.path.join(DIR_NAME, 'input/spending.csv'))
print(df_spending.shape)

(22525715, 12)

In [5]:
df_spending_2020 = df_spending[
    (df_spending['決算年度'] == 2020)&
    ((df_spending['団体名'].str.endswith('市')) | (df_spending['団体名'].str.endswith('区')) | 
     (df_spending['団体名'].str.endswith('町')) | (df_spending['団体名'].str.endswith('村')))
].rename(columns={'県名':'都道府県名', '団体名': '市区町村名'})

In [6]:
# 団体コードのチェックデジットを削除
df_spending_2020['団体コード'] = df_spending_2020['団体コード'].str[:-1].astype(int)

In [9]:
df_expenditure = pd.pivot_table(
    df_spending_2020, 
    index=['都道府県名', '市区町村名', '団体コード'], 
    columns='費目', 
    values='金額', aggfunc='sum'
).reset_index().sort_values('団体コード')
print(df_expenditure.shape)

(1741, 94)

In [10]:
df_expenditure

費目,都道府県名,市区町村名,団体コード,001:労働費・総額,001:土木費・総額,001:歳出合計,001:民生費・総額,001:消防費,001:災害復旧費・総額,001:議会費,...,019:災害復旧費・その他・公立学校,020:災害復旧費・その他・公営住宅,021:災害復旧費・その他・社会福祉施設,022:災害復旧費・その他・その他,023:公債費,024:諸支出金・総額,025:諸支出金・普通財産取得費,026:諸支出金・公営企業費,027:諸支出金・市町村たばこ税都道府県交付金,028:前年度繰上充用金
208,北海道,札幌市,1100,4142428,487856217,4355244196,1379032391,67519188,17072009,5913804,...,0,0,0,0,269310333,20970508,676936,20293572,0,0
143,北海道,函館市,1202,726451,45916799,562569590,189278096,13630546,151296,1410389,...,0,0,0,151296,38411055,1478196,0,1478196,0,0
180,北海道,小樽市,1203,314692,24068891,245835908,77645443,11154117,0,1059654,...,0,0,0,0,15541302,0,0,0,0,0
203,北海道,旭川市,1204,580642,70607812,681049463,233947439,14220148,960,1862613,...,0,0,0,0,52257858,0,0,0,0,0
176,北海道,室蘭市,1205,224601,27357236,191018772,54957050,5882847,0,776991,...,0,0,0,0,14121450,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1062,沖縄県,久米島町,47361,0,2421502,33201798,4627195,988763,17610,253925,...,0,0,0,0,1972851,0,0,0,0,0
1067,沖縄県,八重瀬町,47362,0,2277004,63115464,19105664,1775586,0,335392,...,0,0,0,0,4059642,0,0,0,0,0
1077,沖縄県,多良間村,47375,0,959166,14703621,597366,32291,0,128793,...,0,0,0,0,775422,0,0,0,0,0
1091,沖縄県,竹富町,47381,0,3765272,34577828,8551977,313261,0,311176,...,0,0,0,0,2264847,0,0,0,0,0
1060,沖縄県,与那国町,47382,0,1333838,17776154,2313702,45479,170495,185727,...,0,0,0,0,923220,0,0,0,0,0

In [11]:
df_expenditure.to_csv(os.path.join(DIR_NAME, 'intermediate/expenditure.csv'), index=False)